### ISSUE TITLE
Brief Usage Docs

### ISSUE THREAD

**Issue by ydennisy** [digitalbazaar/credential-handler-polyfill#1]
Hello!
Great initiative on this polyfill.
Could you please add some very brief usage docs on how to get testing with this?
Thanks,
D

**Comment by mattcollier** [comment]
Hello @ydennisy I think this repo would be a good place to start: https://github.com/digitalbazaar/credential-handler-demo

That has the code for all the components demonstrated in this demo: https://credential-repository.demo.digitalbazaar.com/

**Comment by dlongley** [comment]
There's also the API repo: https://github.com/w3c-ccg/credential-handler-api

And the spec:

https://w3c-ccg.github.io/credential-handler-api

But we do need to add some dev docs like we have for the payment handler polyfill:

https://github.com/digitalbazaar/payment-handler-polyfill

I will try to get to that when I have time. But, the credential handler API works very similarly to the payment handler API because it was modeled after it. Note that there are "show technical details" links on each page of the credential handler demo as well.

**Comment by mandyvenables** [comment]
Thanks for your question, since reference docs have been provided this issue will be closed.
