### ISSUE TITLE
Wallet demo doesn't work due to 403 on XHR

### ISSUE THREAD

**Issue by orbmis** [digitalbazaar/credential-handler-polyfill#15]
The demo at https://chapi-demo-wallet.digitalbazaar.com/ doesn't seem to work.  Upon inspection it seems that there is a problem with the http request to the mediator, which is returning a 403 Forbidden:

https://beta.authn.io/mediator?origin=https%3A%2F%2Fchapi-demo-wallet.digitalbazaar.com

**Comment by dmitrizagidulin** [comment]
Hi @simbro, thank you for the heads up. The demo site seems to be working for me, and for several other developers I reached out to. 

So, let's troubleshoot.

1. What Browser (version and OS etc) are you using?
2. Do you have any security browser extensions like Privacy Badger installed? (if yes, you'll need to whitelist the site)
3. Are you behind any kind of firewall?

**Comment by orbmis** [comment]
Apologies Dmitri, it turns out that it is an issue with our corporate firewall, which I hadn't realized at first because I can visit beta.authn.io/mediator in my browser.

I am however seeing an issue whereby a http request to "https://authn.io/manifest?host=localhost:8080" is returning a 404 when I try to run the demo locally.  This is happening when I'm not behind any proxy - could this be an issue of using "localhost" instead of some domain (i.e. via a host file entry)?

**Comment by dlongley** [comment]
@simbro,

> I am however seeing an issue whereby a http request to "https://authn.io/manifest?host=localhost:8080" is returning a 404 when I try to run the demo locally. This is happening when I'm not behind any proxy - could this be an issue of using "localhost" instead of some domain (i.e. via a host file entry)?

Yes, that's happening because the mediator (at authn.io) is trying to get a web app manifest for your website, but it doesn't resolve `localhost` the same way your machine does (it obviously resolves it against itself). The mediator tries to get a web app manifest (manifest.json) to obtain icon and application name information for your site to display in the CHAPI UI to the user. If it can't get a web app manifest, it will use a `favicon.ico` for the site and its domain name.

You will have to host your site somewhere that authn.io can reach in order for it to be able to use your site's manifest.json, if it has one. Note that this isn't a fatal error, however.

**Comment by mattcollier** [comment]
@dlongley folks in this situation might also be able to run a local dev version of authorization.io right?

https://github.com/digitalbazaar/authorization.io

**Comment by orbmis** [comment]
> You will have to host your site somewhere that authn.io can reach in order for it to be able to use your site's manifest.json, if it has one. Note that this isn't a fatal error, however.

If this isn't a fatal error then there must be some other reason that running it locally prevents it from working.  As per @mattcollier suggestion I've tried to run [authoriation.io](https://github.com/digitalbazaar/authorization.io) locally in dev mode, however I can't seem to configure it to stop redirecting to https. I need a valid SSL cert to eliminate the possibility that this is triggering browser security exceptions.

This is what I'm tying to achieve:

 * run authorization.io locally, without SSL, and with an accompanying hosts file entry.
 * run it behind a reverse proxy with a valid SSL cert for the hostname I've chosen.
 * run the chapi-demo-wallet app, having configured the MEDIATOR and WALLET_LOCATION configurations to point to the respective locally running instances.

I think this should be enough to get it up and running, but I'm blocked at the point of turning off SSL (force redirect to https) on the autorization.io app.  I've read through the docs for [bedrock](https://www.npmjs.com/package/bedrock), [bedrock-express](https://www.npmjs.com/package/bedrock-express) etc. but I can't seem to find where this is configured in autorization.io

Note that this issue would affect deployments inside private networks as well (i.e. behind corporate firewalls where authn.io couldn't reach), and not just locally running instances.

**Comment by orbmis** [comment]
To update, in case others find this useful:

I was able to turn off forced-ssl in the autorization.io app by adding this code into 'authorization.dev.js':

```
// only run application on HTTP port
bedrock.events.on('bedrock-express.ready', app => {
  // attach express to regular http
  require('bedrock-server').servers.http.on('request', app);
  // cancel default behavior of attaching to HTTPS
  return false;
});
```

before `bedrock.start()` on the last line.

I also changed the `config.server.domain` parameter in the _lib/config.js_ file to my own host, where I deployed the authorization.io instance.

That allowed me to run an instance of authorization.io behind an nginx reverse proxy, which allowed me to add my own SSL certs.

I then ran the following instances behind the same reverse proxy, but on different ports:

 * chapi-demo-issuer
 * chapi-demo-verifier
 * chapi-demo-wallet

In each case I changed the `MEDIATOR` constant in the JavaScript in each _index.html_ file, and changed the `MEDIATOR` and `WALLET_LOCATION` in the _config.js_ file in the chapi-demo-wallet project to match the hostname I deployed to.

This process allowed to eliminate any proxy issues, as everything was deployed behind our corporate proxy.  Secondly it allowed to preclude any SSL issues, as everything was served over https from the same domain.

The result is that on each page I receive the same error:

> Error in registerWalletWithBrowser: DOMException: "Loading Web application window timed out."

@dlongley  Are you familiar with this error?  Do you know what might be causing it?

**Comment by orbmis** [comment]
Can anyone explain what the role of the mediator site is exactly?  It seems that the Credential Handler Polyfill creates an iframe in which it loads the mediator site (in the demo's case is authn.io), and the mediator site installs a service worker on it's domain.  Anyone using the Credential Handler Polyfill library is essentially opening an iframe to the same mediator site, but any requests to the mediator site are intercepted and handled by the service worker, which contains the logic for displaying prompts to the user and handling storage and retrieval of credentials.  Is this correct?

**Comment by dlongley** [comment]
@simbro,

> If this isn't a fatal error then there must be some other reason that running it locally prevents it from working. As per @mattcollier suggestion I've tried to run authoriation.io locally in dev mode, however I can't seem to configure it to stop redirecting to https. I need a valid SSL cert to eliminate the possibility that this is triggering browser security exceptions.
> 
> ...run authorization.io locally, without SSL, and with an accompanying hosts file entry.

The site can't be run without SSL. SSL is required for the browser features used. In development mode, you just have to deal with browser security exceptions (when not using valid SSL certs). I also don't recommend running authorization.io on localhost for development anyway -- unless you're trying to develop on the mediator itself, which I do not think you're trying to do. You're likely to see one or more prohibitive DOMExceptions when trying to get around SSL. We can try to surface these better in the polyfill, but the point is that certain browser features do not work without running the code in a "secure context".

You should use the live mediator (authn.io) when developing any software that isn't the mediator itself. You should be able to do all of the development you need that way, even if you're developing sites that only run on localhost. The only catch if developing using localhost is you won't be able to see `manifest.json` icons and application names show up in the CHAPI UI. If you want to see that, you will need to serve your development sites via a URL that authn.io can access.

> Can anyone explain what the role of the mediator site is exactly? It seems that the Credential Handler Polyfill creates an iframe in which it loads the mediator site (in the demo's case is authn.io), and the mediator site installs a service worker on it's domain. Anyone using the Credential Handler Polyfill library is essentially opening an iframe to the same mediator site, but any requests to the mediator site are intercepted and handled by the service worker, which contains the logic for displaying prompts to the user and handling storage and retrieval of credentials. Is this correct?

The implementation details are slightly off, but the concept is generally right.

In the CHAPI architecture, the "Mediator" role refers to a piece of software that stores registrations of credential handlers and surfaces a UI to allow the user to select them. The browser will eventually play this role (once CHAPI is fully implemented in browsers), but until then, a polyfill mediator is provided via the website "authn.io". This website serves a mediator Web application that runs everything client side (in the user's browser), including storing credential handler registrations in browser storage. It must run in a neutral domain, separate from websites that run the Credential Handler Polyfill in their own Web applications (e.g., wallets, issuers, verifiers). When these other sites call the CHAPI API, their requests and responses are directed through the polyfill mediator Web app, just as they would be through the browser's mediator software, if it were implemented.

The only part of the polyfill mediator application that runs on the server is the proxy service for retrieving `manifest.json` files -- and this is only because the browser prohibits Web applications from retrieving them from other origins. This is also what causes the only snag when developing wallets, issuers, or verifiers using localhost only websites.

**Comment by orbmis** [comment]
Thanks for the reply @dlongley that really helps.  In terms of SSL issues, I actually deployed the demo site and the mediator site to a development machine, and served everything over https to eliminate any SSL related issues.

Unfortunately using "authn.io" doesn't seem to work behind a corporate proxy, so that's why I deployed a custom instance inside our network.  From what you're describing it would seem that if  my instance of "authn.io" was unable to resolve the requesting site (i.e. the demo site) then that would cause everything to fail.

**Comment by dlongley** [comment]
> From what you're describing it would seem that if my instance of "authn.io" was unable to resolve the requesting site (i.e. the demo site) then that would cause everything to fail.

The only time "authn.io" (or your instance of it) does its own resolution is when retrieving a site's manifest.json (which is not a requirement for functionality). Otherwise, all calls come directly from your browser from within the mediator Web application, i.e., your browser will do the resolution using whatever rules it is configured with. If your browser can't access a site for any reason, then the mediator Web app won't be able to either, as it's all running locally. The mediator Web app is designed to be as close as possible to a real "polyfill" for code running inside your browser. Hopefully this is helpful.

**Comment by orbmis** [comment]
Thanks for all help with this issue, very much appreciated.  Whatever is causing the polyfill to fail must be something to do with the security restrictions on our network. If I uncover any more info I'll feed it back to you in case it's useful.
