### ISSUE TITLE
Credential subject identification and/or authentication

### ISSUE THREAD

**Issue by clehner** [digitalbazaar/credential-handler-polyfill#17]
If an issuer wants to issue a verifiable credential to a user where the [credential subject = holder](https://w3c.github.io/vc-data-model/#subject-is-the-holder), they must first know the user's `id` to put in the `credentialSubject`. The examples here assume the issuer already knows the user's `id`. Is CHAPI and/or this polyfill and demo applications intended to allow for querying for the user's `id`?

The [demo wallet](https://github.com/digitalbazaar/chapi-demo-wallet) supports query type `QueryByExample` in the CHAPI `get` call. [VP Request Spec](https://github.com/w3c-ccg/vp-request-spec/) describes [QueryByExample](https://w3c-ccg.github.io/vp-request-spec/#query-by-example), and also another query type, [DIDAuth](https://w3c-ccg.github.io/vp-request-spec/#did-authentication-request), which appears to be for proving control of a DID by issuing a VP without a VC. Being based on VPs, it seems that fits with existing usage of VPs in CHAPI. Using such a `DIDAuth` query would allow the issuer to identify the user and authenticate them if the id is a DID. Is this a supported or intended use for CHAPI and this polyfill?

**Comment by dlongley** [comment]
> Using such a DIDAuth query would allow the issuer to identify the user and authenticate them if the id is a DID. Is this a supported or intended use for CHAPI and this polyfill?

Yes, this is a supported and intended use of CHAPI and this polyfill.

**Comment by clehner** [comment]
Thanks @dlongley, that is good to know. I guess this issue can be closed then, unless you think there should be something to note this use case, e.g. in the readme.

**Comment by dlongley** [comment]
It would be useful to have a link to the VP request spec and an example showing DIDAuth usage. I'll leave it open for now for someone to submit a PR for that and will close if we don't see one in due time.

**Comment by tsnyder-gs1us** [comment]
Does anyone have an example of passing a DIDAuth request. I tried the following and got back null.

    const authQuery = 
    {
      "query": [{
        "type": 'DIDAuth'
      }],
      "challenge": '99612b24-63d9-11ea-b99f-4f66f3e4f81a',
      "domain": 'example.com'
    }

    const result = await navigator.credentials.get(authQuery);
    console.log(result);

**Comment by dlongley** [comment]
So there's a bit more that's needed when passing a request to `navigator.credentials.get`. The reason why is that CHAPI (Credential Handler API) extends the Credential Management API in web browsers. The Credential Management API supports a few types of "Credentials" where a "Credential" refers to something much more broad than a Verifiable Credential, for example, it includes "passwords".

So the Credential Management API (which provides `navigator.credentials.get`) lets you ask for a password from the browser's password manager, ask for a saved facebook login credential, ask for two-factor authentication, AND it lets you ask for a "WebCredential" via a digital wallet via CHAPI. So when you pass a request into `navigator.credentials.get`, you have to say if you want, for example, a `password` or a `web` credential. Here we want a `web` credential because we're trying to use CHAPI.

Specifically, the type of `web` credential we want is a "VerifiablePresentation". Again, this terminology is confusing, because the word "credential" is being reused for so many different things -- and none of them, thus far, is a "W3C Verifiable Credential". You don't actually ask for those directly, you ask for a "VerifiablePresentation" that includes them (or that includes a DID Auth proof, or anything else you want to present from your digital wallet).

So, all that being said, I think this should work better:

```js
const request = {
  // we want a "web" credential via CHAPI, not a "password" credential
  // via the browser's password manager
  web: {
    // the type of "web" credential is a "VerifiablePresentation"
    VerifiablePresentation: {
      // *now* here is where the VPR spec comes in with the
      // example you were trying to use... so all the other examples
      // should be nested in here as well
      query: {
        type: 'DIDAuth'
      },
      challenge: '99612b24-63d9-11ea-b99f-4f66f3e4f81a',
      domain: 'example.com'
    }
  }
};
const result = await navigator.credentials.get(request);
console.log(result);
```

Hope this works and clarifies things. There are several layers here to all this browser tech.

**Comment by dlongley** [comment]
Closing this now that there is a link to [chapi.io](https://chapi.io) which provides a much better place for explaining usage with demos, examples, etc.
