### ISSUE TITLE
Cannot import in nextjs / typescript application

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/credential-handler-polyfill#24]
```
import * as polyfill from 'credential-handler-polyfill';
```

Error:

```
SyntaxError: Cannot use import statement outside a module
```

Likely related to ES modules.

**Comment by dmitrizagidulin** [comment]
Yeah, I think this may have changed in v3.0. I was able to use it in typescript as of v2.3.0

**Comment by OR13** [comment]
I tried this as well:

```
 <script src="https://unpkg.com/credential-handler-polyfill@2.1.0/dist/credential-handler-polyfill.min.js"></script>
```

Then later:

```
  const polyfill = window.credentialHandlerPolyfill;
  console.log("polyfill", polyfill);
```
<img width="750" alt="Screen Shot 2022-07-12 at 11 17 44 AM" src="https://user-images.githubusercontent.com/8295856/178542593-7c268305-40cd-4b51-9b71-67af90ea710f.png">


Expect to get a default export with useful interfaces, observed this instead.

**Comment by OR13** [comment]
update readme to look like this:

```
const polyfill = await window.credentialHandlerPolyfill.load();
```

**Comment by dlongley** [comment]
@davidlehn, any insights here? Do we just need to update the `package.json` with some missing field like `exports` to resolve the direct import? Regarding the `unpkg` CDN, I don't know how it builds minimal scripts.

Regardless, we have used both the `unpkg` CDN version with a script tag and imported via webpack without issue.

@OR13,

> SyntaxError: Cannot use import statement outside a module

That sounds like you're trying to import from a CJS environment. You can do a dynamic import there, of course: `import(...)`. The polyfill needs to be dynamically loaded regardless ... and its API is available from globals, so that should be one way to use it if you are in a CJS environment.

**Comment by dlongley** [comment]
@dmitrizagidulin,

> I was able to use it in typescript as of v2.3.0

Please make sure you're using `v2.3.1` to get bug fixes.

**Comment by dmitrizagidulin** [comment]
@dlongley thanks, will do.

**Comment by dlongley** [comment]
@OR13,

I added some updates to the README on the loading section to try and make it more clear.

**Comment by OR13** [comment]
if there is a way to float the lastest version via cdn thats what the readme should propose first imo.

**Comment by dlongley** [comment]
README now uses floating version 3, closing.
