### ISSUE TITLE
Error: Permission denied.

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/credential-handler-polyfill#28]
```
  // site asks permission to be a credential handler for the user
  const result = await CredentialManager.requestPermission();
  if(result !== 'granted') {
    throw new Error('Permission denied.');
  }
  ```
  
  Google Chrome Version 104.0.5112.79 (Official Build) (x86_64)
  Using Self Signed Cert so that manifest URL will load of localhost:
 
  https://localhost:3000/manifest.json
  
  Popup does not display, and permission is denied... Works in:
  
  Brave Version 1.16.75 Chromium: 86.0.4240.193 (Official Build) (x86_64)
  
  I also see the error 
  ```
  "AllowWalletDialog~HintChooser~Mediator.5590bfea6bcaa4a4efbd.js:2 Missing Web app manifest."
  ```

**Comment by dlongley** [comment]
Is the Web app manifest served with CORS headers? If not, it needs to be, as mentioned in the docs [here](https://github.com/credential-handler/credential-handler-polyfill/blob/main/README.md#serving-a-manifestjson-web-app-manifest).

**Comment by dlongley** [comment]
Hmm, actually, I presume that if it's working in Brave that the CORS headers are set. So there must be something else going on in your local browser environment in Chrome. Have you tried with private browsing mode / using a guest account on the same Chrome version to avoid any other potential confounds?

**Comment by dlongley** [comment]
Btw, the process for testing with a self-signed cert, if not imported into your browser, is that you'll need to visit the site using it and accept the exception before doing anything else.

**Comment by OR13** [comment]
I have tried, private browsing, guest mode, disabling all extensions.

I am pretty sure its related to the self signed cert part, since it works with proper certs.

**Comment by OR13** [comment]
```
 "credential-handler-polyfill": "3.0.0",
 "web-credential-handler": "2.0.0",
 ```

**Comment by OR13** [comment]
Also worth noting, other team members can't reproduce, so it may yet be something specific to my host.

**Comment by dlongley** [comment]
I was able to reproduce this using Chrome 104.x and running a local clone of a fresh https://github.com/credential-handler/chapi-demo-wallet.

Chrome 104.x reports to me in the devtools console that you need to have this CORS header set to access localhost over CORS:

`Access-Control-Allow-Private-Network: true`

As a quick hack, I set this in the local http-server (the npm package used for local development in that repo) by adding this line:

```
this.headers['Access-Control-Allow-Private-Network'] = 'true';
```

Around here: https://github.com/http-party/http-server/blob/51204e1955233b68a23fa5390d99619f4c61e0a6/lib/http-server.js#L104

I didn't see a command line option for adding headers generally using `http-server`, but I didn't look too hard so may have missed it. After this change and clearing the authn.io local browser cache it uses for manifest.json files, I no longer experienced any issues.

So, if you don't have that set in your localhost dev server, make sure it's set. Then, make sure the authn.io local cache has been cleared by visiting authn.io in a separate tab in Chrome, opening the devtools, and going to `Cache Storage`. If there's a cache storage entry there for `authn.io-1 - https://autn.io` you can go ahead and safely clear all of its entries (or selectively just clear the one you have for `localhost:3000`, if present). Note: Cache entries auto-expire after 5 minutes.

Another alternative to setting the additional CORS private network header is to add an `/etc/hosts` entry for localhost with some fake domain and then visit that one instead of localhost. We commonly do this when testing the polyfill to ensure that the browser sees different domains and triggers the appropriate browser behavior we need to test.

**Comment by OR13** [comment]
Thanks, I will see how much control over the web server I have, and see if I can resolve it.

There is some conjecture that this may be related to react / create react app versions above and below 18.

**Comment by dlongley** [comment]
Closing as a solution is given above for dev environments.
