### ISSUE TITLE
Query whether wallet is installed already / Wallet cleanup

### ISSUE THREAD

**Issue by brianorwhatever** [digitalbazaar/credential-handler-polyfill#32]
As far as I can tell there is no mechanism to determine if a wallet has already been installed (for disabling the install button for example).

It does appear with my production wallet that it doesn't allow duplicating the wallet so when I install it again it doesn't have duplicates.. however in my local testing (through ngrok) I did add a number of what looked like the same wallet but there was probably slight tweaks.

How does it determine that the wallet is unique?

Further to this I am now unable to hide the local wallets.. I continuously click hide and it disappears until I open the wallet selector again and it's back. Is there a way to cleanup my installed wallets?

**Comment by dlongley** [comment]
@brianorwhatever,

> As far as I can tell there is no mechanism to determine if a wallet has already been installed (for disabling the install button for example).

Yes, there's no way to do this without just making a call to register the wallet again. This is the only behavior that can be consistently implemented across all browsers. Some browsers don't let you check without "transient user activation", e.g., a click, some don't let you check without a popup window, and so on.

The chapi.io instructions should say (if they don't already) that wallet providers should have some kind of message in their interfaces like "Need to register your wallet?" or "Wallet not showing up as a choice on other sites?" (language obviously to be determined by the wallet provider). Clicking that message should attempt another registration.

> How does it determine that the wallet is unique?

Wallets are unique based on Web origin (e.g., `https://example.com`, `https://example.com:34732`, `https://foo.example.com`). If, for any reason, you see a case where more than one wallet is registered under the same origin, that's a bug we'll need to fix.

> Further to this I am now unable to hide the local wallets.. I continuously click hide and it disappears until I open the wallet selector again and it's back. Is there a way to cleanup my installed wallets?

Clicking hide should remove the registered wallet from the selector. If a particular wallet origin is recommended in the current request it can show up again, but it should say `Recommended by <relying party>` in small text under the option. Otherwise, perhaps you discovered a new bug! If you're unable to remove wallets via the interface and it's unrelated to recommended options, please file a bug and let us know your browser brand and version and whatever other information that might enable us to resolve it more quickly like simplified reproduction steps.

You can always clear all your installed wallets by visiting authn.io and clearing the site storage there. Of course, this is not for regular users -- it's really something only developers would know how to do.

**Comment by dlongley** [comment]
Closing given the explanation above.
